use std::fmt;

#[derive(Clone, Copy)]
pub enum Inst {
    Mov(u8, u8),
    IAdd(u8, u8, u8),
    ISub(u8, u8, u8),
    IMul(u8, u8, u8),
    IDiv(u8, u8, u8),
    IRem(u8, u8, u8),
    IPow(u8, u8, u8),
    FAdd(u8, u8, u8),
    FSub(u8, u8, u8),
    FMul(u8, u8, u8),
    FDiv(u8, u8, u8),
    FRem(u8, u8, u8),
    FPow(u8, u8, u8),
    SbS(u8, u8),
    ShS(u8, u8),
    SwS(u8, u8),
    SdS(u8, u8),
    LbS(u8, u8),
    LhS(u8, u8),
    LwS(u8, u8),
    LdS(u8, u8),
    LbuS(u8, u8),
    LhuS(u8, u8),
    LwuS(u8, u8),
    SbM(u8, u8),
    ShM(u8, u8),
    SwM(u8, u8),
    SdM(u8, u8),
    LbM(u8, u8),
    LhM(u8, u8),
    LwM(u8, u8),
    LdM(u8, u8),
    LbuM(u8, u8),
    LhuM(u8, u8),
    LwuM(u8, u8),
}

impl fmt::Debug for Inst {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Mov(dest, src) => write!(f, "mov r{dest}, r{src}"),
            Self::IAdd(dest, src1, src2) => write!(f, "iadd r{dest}, r{src1}, r{src2}"),
            Self::ISub(dest, src1, src2) => write!(f, "isub r{dest}, r{src1}, r{src2}"),
            Self::IMul(dest, src1, src2) => write!(f, "imul r{dest}, r{src1}, r{src2}"),
            Self::IDiv(dest, src1, src2) => write!(f, "idiv r{dest}, r{src1}, r{src2}"),
            Self::IRem(dest, src1, src2) => write!(f, "irem r{dest}, r{src1}, r{src2}"),
            Self::IPow(dest, src1, src2) => write!(f, "ipow r{dest}, r{src1}, r{src2}"),
            Self::FAdd(dest, src1, src2) => write!(f, "fadd r{dest}, r{src1}, r{src2}"),
            Self::FSub(dest, src1, src2) => write!(f, "fsub r{dest}, r{src1}, r{src2}"),
            Self::FMul(dest, src1, src2) => write!(f, "fmul r{dest}, r{src1}, r{src2}"),
            Self::FDiv(dest, src1, src2) => write!(f, "fdiv r{dest}, r{src1}, r{src2}"),
            Self::FRem(dest, src1, src2) => write!(f, "frem r{dest}, r{src1}, r{src2}"),
            Self::FPow(dest, src1, src2) => write!(f, "fpow r{dest}, r{src1}, r{src2}"),
            Self::SbS(dest, src) => write!(f, "sbs r{dest}, r{src}"),
            Self::ShS(dest, src) => write!(f, "shs r{dest}, r{src}"),
            Self::SwS(dest, src) => write!(f, "sws r{dest}, r{src}"),
            Self::SdS(dest, src) => write!(f, "sds r{dest}, r{src}"),
            Self::LbS(dest, src) => write!(f, "lbs r{dest}, r{src}"),
            Self::LhS(dest, src) => write!(f, "lhs r{dest}, r{src}"),
            Self::LwS(dest, src) => write!(f, "lws r{dest}, r{src}"),
            Self::LdS(dest, src) => write!(f, "lds r{dest}, r{src}"),
            Self::LbuS(dest, src) => write!(f, "lbus r{dest}, r{src}"),
            Self::LhuS(dest, src) => write!(f, "lhus r{dest}, r{src}"),
            Self::LwuS(dest, src) => write!(f, "lwus r{dest}, r{src}"),
            Self::SbM(dest, src) => write!(f, "sbm r{dest}, r{src}"),
            Self::ShM(dest, src) => write!(f, "shm r{dest}, r{src}"),
            Self::SwM(dest, src) => write!(f, "swm r{dest}, r{src}"),
            Self::SdM(dest, src) => write!(f, "sdm r{dest}, r{src}"),
            Self::LbM(dest, src) => write!(f, "lbm r{dest}, r{src}"),
            Self::LhM(dest, src) => write!(f, "lhm r{dest}, r{src}"),
            Self::LwM(dest, src) => write!(f, "lwm r{dest}, r{src}"),
            Self::LdM(dest, src) => write!(f, "ldm r{dest}, r{src}"),
            Self::LbuM(dest, src) => write!(f, "lbum r{dest}, r{src}"),
            Self::LhuM(dest, src) => write!(f, "lhum r{dest}, r{src}"),
            Self::LwuM(dest, src) => write!(f, "lwum r{dest}, r{src}"),
        }
    }
}